[project]
name = "neuralvoid"
version = "0.1.0"
description = "NeuralCore framework for AI applications"
readme = "README.md"
authors = [
    { name = "Abyss-c0re", email = "dev@abyss-core.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "beautifulsoup4>=4.14.3",
    "ddgs>=9.12.0",
    "neuralcore @ git+https://github.com/Abyss-c0re/NeuralCore.git",
    "textual>=0.81.1",
]

[tool.pyright]  
venvPath = "."     
venv = ".venv"
extraPaths = ["../NeuralCore"]

[project.scripts]
neuralvoid = "neuralvoid.main:main"

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0", "toml>=0.10.2"]
build-backend = "uv_build"


